name: Auto Merge Dev to Main

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Merge with main
        env:
          GITHUB_TOKEN: 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
        run: |
          git clone https://github.com/whoami-anoint/new.git tmp
          cd tmp
          git config user.name "whoami-anoint"
          git config user.email "abhishekkfl@gmail.com"
          git pull origin main
          git checkout main
          git merge dev
          git push origin main
