echo 'name: Auto Merge

on:
  schedule:
    - cron:  '*/2 * * * *'

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Merge dev into main
        run: |
          git checkout main
          git merge --no-ff dev
          git push origin main
