name: Merge Dev into Main

on:
  schedule:
    - cron: '*/2 * * * *'  # Runs every 2 minutes

jobs:
  merge:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Merge Dev into Main
        run: |
          bash scripts/merge_script.sh
