name: Automerge

on:  
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Merge with main
        env:
          GITHUB_TOKEN: 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
        run: |
          git clone https://github.com/whoami-anoint/new.git tmp
          cd tmp
          git config user.name "whoami-anoint"
          git config user.email "abhishekkfl@gmail.com"
          git checkout main
          git pull
          git checkout dev
          git merge origin/dev
          git push origin dev:main
